CREATE TABLE laad_data.patient (
  PATIENT_ID NUMERIC PRIMARY KEY,
  PAT_BRTH_YR_NBR NUMERIC(4),
  PAT_GENDER_CD VARCHAR(1)
);


CREATE TABLE laad_data.provider (
  provider_id NUMERIC PRIMARY KEY,
  provider_typ_id NUMERIC,
  org_nm VARCHAR(70),
  ims_rxer_id VARCHAR(7),
  last_nm VARCHAR(50),
  first_nm VARCHAR(50),
  addr_line1_txt VARCHAR(150),
  addr_line2_txt VARCHAR(150),
  city_nm VARCHAR(50),
  st_cd VARCHAR(2),
  zip VARCHAR(5),
  pri_spcl_cd VARCHAR(4),
  pri_spcl_desc VARCHAR(150),
  me_nbr VARCHAR(10),
  npi VARCHAR(10)
  );



CREATE TABLE laad_data. products (
  PRODUCT_ID NUMERIC PRIMARY KEY,
  NDC_CD CHAR(11),
  MKTED_PROD_NM VARCHAR(35),
  STRNT_DESC VARCHAR(60),
  DOSAGE_FORM_NM VARCHAR(80),
  CMF_PROD_NBR VARCHAR(7),
  CMF_PACK_NBR VARCHAR(3),
  USC_CD VARCHAR(5),
  USC_DESC VARCHAR(50)
);


CREATE TABLE laad_data. plan (
  PLAN_ID NUMERIC PRIMARY KEY,
  IMS_PLN_ID NUMERIC(4),
  IMS_PLN_NM VARCHAR(32),
  IMS_PAYER_ID NUMERIC(6),
  IMS_PAYER_NM VARCHAR(32),
  PLANTRAK_ID VARCHAR(10),
  MODEL_TYP_CD VARCHAR(15),
  MODEL_TYP_NM VARCHAR(100)
);


CREATE TABLE laad_data. procedure (
PRC_CD  VARCHAR(10)PRIMARY key,
PRC_VERS_TYP_ID  numeric,
PRC_SHORT_DESC  VARCHAR(100),
PRC_TYP_CD  VARCHAR(1)
);

CREATE TABLE laad_data. procedure_modifier(
PRC_MODR_CD  VARCHAR(2)PRIMARY key,
PRC_MODR_DESC  VARCHAR(2000)
);


CREATE TABLE laad_data. diagnosis(
DIAG_CD VARCHAR(10)	,
DIAG_VERS_TYP_ID numeric,	
DIAG_SHORT_DESC	VARCHAR(100)
);



CREATE TABLE laad_data. Rx_claim (
  MONTH_ID NUMERIC,
  SVC_DT DATE,
  PATIENT_ID NUMERIC,
  PAT_ZIP3 VARCHAR(3),
  CHNL_CD CHAR(1),
  CLAIM_ID NUMERIC PRIMARY KEY,
  RX_TYP_CD NUMERIC(1),
  PROVIDER_ID NUMERIC,
  PLAN_ID NUMERIC,
  PAY_TYP_DESC VARCHAR(50),
  PRODUCT_ID NUMERIC,
  DSPNSD_QTY NUMERIC(10,3),
  DAYS_SUPPLY_CNT NUMERIC(10,3),
  PAT_PAY_AMT NUMERIC(10,2)
);


CREATE TABLE laad_data. Dx_claim(
MONTH_ID  numeric,
SVC_DT  DATE,
PATIENT_ID  numeric,
PAT_ZIP3  VARCHAR(3),
CLAIM_ID  NUMERIC PRIMARY key,
SVC_NBR  numeric,
DIAG_CD_POSN_NBR  numeric,
CLAIM_TYP_CD  VARCHAR(1),
RENDERING_PROVIDER_ID  numeric,
REFERRING_PROVIDER_ID  numeric,
BILLING_PROVIDER_ID  numeric,
FACILITY_PROVIDER_ID  numeric,
PLACE_OF_SVC_NM  VARCHAR(100),
PLAN_ID  numeric,
PAY_TYP_DESC  VARCHAR(50),
DIAG_CD  VARCHAR(10),
DIAG_VERS_TYP_ID  numeric,
PRC_CD  VARCHAR(10),
PRC_VERS_TYP_ID  numeric,
PRC1_MODR_CD  VARCHAR(2),
PRC2_MODR_CD  VARCHAR(2),
PRC3_MODR_CD  VARCHAR(2),
PRC4_MODR_CD  VARCHAR(2),
NDC_CD  VARCHAR(11),
SVC_CRGD_AMT  NUMERIC(12,2),
UNIT_OF_SVC_AMT  NUMERIC(15,2)
);

CREATE TABLE laad_data. Dx_p_provider(
MONTH_ID  numeric,
PROVIDER_ID  NUMERIC PRIMARY key,
TIER_ID  NUMERIC);



CREATE TABLE laad_data. patient_act(
MONTH_ID  VARCHAR(6),
PATIENT_ID   numeric,
DATA_TYP_CD  NUMERIC);


select * from laad_data.rx_claim rc limit 10


